tasks:
  - name: "Init"
    command: |
      #!/usr/bin/env sh
      set -e
      # Download V
      if [ ! -e 'v/' ]
      then
        git clone https://github.com/vlang/v
      fi
      # Make V
      cd v
      if [ ! -e './v' ]
      then
        make
      fi
      # Symlink V
      sudo ./v symlink
      cd ..
      # Download Clockwork
      if [ ! -e 'clockwork/' ]
      then
        git clone https://github.com/EmmaTheMartian/clockwork --recursive
      fi
      # Build and install Clockwork
      cd clockwork
      ../v/v run . install
      cd ..
      # Install project dependencies
      clockwork deps
